version: "3.9"

services:
  dns:
    build: ./dns
    container_name: dns_server
#    ports:
#      - "53:53/udp"
    volumes:
      - ./dns/zonefile.db:/etc/bind/db.example.com:ro
    restart: unless-stopped

  proxy:
    build: ./proxy
    container_name: proxy_server
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
    restart: unless-stopped

  web1:
    build: ./web1
    container_name: web1_server
    ports:
      - "8081:80"
    restart: unless-stopped

  web2:
    build: ./web2
    container_name: web2_server
    ports:
      - "8082:80"
    restart: unless-stopped
